kind: Ingress
metadata:
  name: manga-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: asyrawih.id 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manga 
                port:
                  number: 80
