apiVersion: v1
kind: Service
metadata:
  name: manga-service
  labels:
    name: manga-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: manga
  selector:
    app: manga
